# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acai < Formula
  desc "Go CLI and MCP server for Granola meeting intelligence"
  homepage "https://github.com/felixgeelhaar/acai"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_darwin_amd64.tar.gz"
      sha256 "81917f1d32b4c653f6c47109534c9c9da1082818cba266f8087997b4999ee24f"

      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_darwin_arm64.tar.gz"
      sha256 "86e4fd21e575cb7b24293c924a35b3842529e9a96324a640311b9b6163c3f96d"

      def install
        bin.install "acai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_linux_amd64.tar.gz"
      sha256 "47fd4e896cdd97cff714beaf4b3016a890da6150c8e35b871cbee8247d5f0923"
      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_linux_arm64.tar.gz"
      sha256 "930e0951d261e492f2d5cd1d585902c2c87fe418e6d6a64697548c93c63e789d"
      def install
        bin.install "acai"
      end
    end
  end
end
