# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acai < Formula
  desc "Go CLI and MCP server for Granola meeting intelligence"
  homepage "https://github.com/felixgeelhaar/acai"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_darwin_amd64.tar.gz"
      sha256 "a3a61dbe4b3cf988f1edd34d73a187dc0ac2e537312bf46fb48185e4c21449d4"

      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_darwin_arm64.tar.gz"
      sha256 "076d71ea9e198093bb83a06f4eb19660dcc60294fe40f934fea6ce7b49bce15c"

      def install
        bin.install "acai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_linux_amd64.tar.gz"
      sha256 "20b551a17658481f7b5182a8ae0f0f4cef00ebc1584396f6735f5431a57b3bec"
      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.1.0/acai_2.1.0_linux_arm64.tar.gz"
      sha256 "65cd262f8bacc2e62a7ee8fb0a00ee61cde0dde95bdf32829b4ff05b7332c133"
      def install
        bin.install "acai"
      end
    end
  end
end
