# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heartbeat < Formula
  desc "MCP server for running team health checks with AI agents"
  homepage "https://github.com/felixgeelhaar/heartbeat"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/heartbeat/releases/download/v1.0.0/heartbeat_darwin_amd64.tar.gz"
      sha256 "e3bc5cf2a94b04fa9b0ca7c81cd650d8aa081bc39c000469fd5e9b26d67027ca"

      define_method(:install) do
        bin.install "heartbeat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/heartbeat/releases/download/v1.0.0/heartbeat_darwin_arm64.tar.gz"
      sha256 "5267ce103ccd4731667b42826d54490a55875839be92aebea861c8ec4d67d02d"

      define_method(:install) do
        bin.install "heartbeat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/heartbeat/releases/download/v1.0.0/heartbeat_linux_amd64.tar.gz"
      sha256 "8e11ae179c92a986e0b3a7c90e5cd4d93e961d904cc6a14bad3fadb43cf13363"
      define_method(:install) do
        bin.install "heartbeat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/heartbeat/releases/download/v1.0.0/heartbeat_linux_arm64.tar.gz"
      sha256 "ec3e04ae881ff2b21d8e09d03a764f6a920aa91a5465465cdf205269302b19c6"
      define_method(:install) do
        bin.install "heartbeat"
      end
    end
  end

  test do
    system "#{bin}/heartbeat", "--help"
  end
end
