# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nox-hq/nox/releases/download/v0.3.0/nox_0.3.0_darwin_amd64.tar.gz"
      sha256 "9b0ac3b2e04e80a0543972a01cf44d039f3f236fdf2bb076e5aaef69bba72c8f"

      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nox-hq/nox/releases/download/v0.3.0/nox_0.3.0_darwin_arm64.tar.gz"
      sha256 "962865cc032ba73165aedd20c735dd9530045d501f04bed093e302a9c7dd73a3"

      def install
        bin.install "nox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.3.0/nox_0.3.0_linux_amd64.tar.gz"
      sha256 "def18ac389e49e2b414d299c17d4c91df37e4ca139b518f9555140e21aaefd4f"
      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.3.0/nox_0.3.0_linux_arm64.tar.gz"
      sha256 "96df10920e19b07f2c6332d83105257aeb119e66f90e54917aa9957ab4f40c32"
      def install
        bin.install "nox"
      end
    end
  end

  test do
    system "#{bin}/nox", "--help"
  end
end
