# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.2/nox_0.4.2_darwin_amd64.tar.gz"
      sha256 "f191c15120ef2df10330797b328a071f2d6722843bd18cc36c1514f1159d1b94"

      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.2/nox_0.4.2_darwin_arm64.tar.gz"
      sha256 "b46066642a6d37b34281f5db846904b7646b47da33512d70b8b0360dadbcdf8f"

      def install
        bin.install "nox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.2/nox_0.4.2_linux_amd64.tar.gz"
      sha256 "b18482b91a3fc98b21dfae2ca39e7abc330cdeaedc0fff730b402e37501ddc08"
      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.2/nox_0.4.2_linux_arm64.tar.gz"
      sha256 "57fe0bc73f70f00818d18cee32d36adc4d20e7d3950537dd0951b1a2b8cd1dd6"
      def install
        bin.install "nox"
      end
    end
  end

  test do
    system "#{bin}/nox", "--help"
  end
end
