# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.0/nox_0.4.0_darwin_amd64.tar.gz"
      sha256 "73614096a36e6101adda6de39c452e83645831e2ad5e81bb301bac6ea500df8e"

      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.0/nox_0.4.0_darwin_arm64.tar.gz"
      sha256 "286df3017f196fe8b47848466381413152b68d3dbdb95d089bc4bf18465df791"

      def install
        bin.install "nox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.0/nox_0.4.0_linux_amd64.tar.gz"
      sha256 "fa0de1f83d6da33714d0878fd1def5150385b16a22effae89da4265cd38457ef"
      def install
        bin.install "nox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.4.0/nox_0.4.0_linux_arm64.tar.gz"
      sha256 "2258319144d6a5418445d06de62407b51cc4beccfdd6c840907a6d237adb6f4b"
      def install
        bin.install "nox"
      end
    end
  end

  test do
    system "#{bin}/nox", "--help"
  end
end
