# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specular < Formula
  desc "AI-Native Spec and Build Assistant with policy enforcement"
  homepage "https://github.com/felixgeelhaar/specular"
  version "1.2.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.2.0/specular_1.2.0_darwin_amd64.tar.gz"
      sha256 "2419cf6a110ba8aadf692cde36fec0f7a4d087fbac87085cf777c5eb0d44553f"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.2.0/specular_1.2.0_darwin_arm64.tar.gz"
      sha256 "9345ed7ad7dcbece20633de62f6e6e9e4670a8c171961b38ae3401db02123b58"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.2.0/specular_1.2.0_linux_amd64.tar.gz"
      sha256 "9cf5189d601997196eafcac437e11cb7ff780e9fe54ed12ffd2199f31be1e433"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.2.0/specular_1.2.0_linux_arm64.tar.gz"
      sha256 "e6451dc2c58cb384af8796af784971d1ce181fd97b28f26abb50fcaa2f37bde8"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  test do
    system "#{bin}/specular", "version"
  end
end
