# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specular < Formula
  desc "AI-Native Spec and Build Assistant with policy enforcement"
  homepage "https://github.com/felixgeelhaar/specular"
  version "1.1.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.1.0/specular_1.1.0_darwin_amd64.tar.gz"
      sha256 "3c37e9b9794ddd33a8c8386832a9e3c7f2e20a8be4c9c5276b7b2dbab942be40"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.1.0/specular_1.1.0_darwin_arm64.tar.gz"
      sha256 "856083ccd19c0391ac75f736b33de92c921062f2f099dab8d9aa1458fee27ccb"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.1.0/specular_1.1.0_linux_amd64.tar.gz"
      sha256 "bd3b87f89ca5820290771ebe3029ed992a8c091efef1ac5d1e07671b3b291512"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.1.0/specular_1.1.0_linux_arm64.tar.gz"
      sha256 "fe356eace5dc1c5c461662475c0760922afe193dd6e619659482c3e6c08dfc53"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  test do
    system "#{bin}/specular", "version"
  end
end
