# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  version "0.117.0"

  on_macos do
    on_intel do
      sha256 "94e42d6bf2181c7c5ccff73ea8a0cae68b58f760ca048a5350865e99f36d2578"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93e8da5d6ad455e4f026e340ff25c8d5d7caadeaea754381947dfe4e01593f18"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "efe85ac923f57352547aff68e7a873d14f5813ce26e79917f48a575e04278aa2"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4bd766047cfe4413064aae02fc20d34aa07f2d11bad6f302a14b3524c2249cb"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemos"
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required

end
