# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  version "0.117.1"

  on_macos do
    on_intel do
      sha256 "957a531636ef295f3f3c8102b3e3c8e6cf7c2839ceffb11410ea93628c7832b3"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c40f703fe9c6fe51225ea628ac83dec5e89c940e48b4497004f53ab77c1a9fe"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "686373f2139e34b0fc8344f6777bf38df77fd033cdfb0f1288bfcf412ba56b4e"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb6d2ef85824cd82a5cf804de500b1677d02206b8af0761c81e8e2f64e9f4834"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemos"
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required

end
