# This file was generated by GoReleaser. DO NOT EDIT.
cask "nox" do
  name "nox"
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nox"

  on_macos do
    on_intel do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_darwin_amd64.tar.gz"
      sha256 "9ea208ab52e6d86940a83346d9334f90381963e87c6bf1ebde53a5836af236b8"
    end
    on_arm do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_darwin_arm64.tar.gz"
      sha256 "5c6d05c71c323e224b31b78c6d43390fa54d5fbb3b872e6a426ac1474aaab56f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_linux_amd64.tar.gz"
      sha256 "e7f6b83259e60fc13bc7fa9c70c84db3b49ba8b2897409b8e253de76946c8ee7"
    end
    on_arm do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_linux_arm64.tar.gz"
      sha256 "2d06ae86ac2a43dd6f2868feb97e7d2675f18976d0bffa9475ef0dffdd63f16f"
    end
  end

  # No zap stanza required
end
