# This file was generated by GoReleaser. DO NOT EDIT.
cask "nox" do
  name "nox"
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nox"

  on_macos do
    on_intel do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_darwin_amd64.tar.gz"
      sha256 "8c0bf4530c9904e861dfb624e5562f2569f6d46236c25e6841d44c0193aef96f"
    end
    on_arm do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_darwin_arm64.tar.gz"
      sha256 "bc6efb202499f7ffe633fc472b5a0ab533e6a32e5a85307a8383b63c637c8c87"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_linux_amd64.tar.gz"
      sha256 "e2c26e641d7c32304866e6840154aa9a4e61517d97270eb5895d566634bac180"
    end
    on_arm do
      url "https://github.com/nox-hq/nox/releases/download/v#{version}/nox_#{version}_linux_arm64.tar.gz"
      sha256 "b14227886e1231e3c3fc10db2a85a8559c7276f2c2a9388bedb90cdef2965e38"
    end
  end

  # No zap stanza required
end
