# This file was generated by GoReleaser. DO NOT EDIT.
cask "preflight" do
  version "4.12.0"

  on_macos do
    on_intel do
      sha256 "2df25f57777406ad8dab2793b33b9f81451fe2047822b492c592728c5a7748e1"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "37b656bff935b1b6284560720f55b8f16f3c548f7a813851d5b229cd92c8e5bf"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18a04d684db76cebbd555c94819c57b4b0bf160dff36691aa1b59b69d3b0a8b2"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "fb5d8e2591f282431c32141028958025c6b09f3c06df4d3a9b51c0c26bb6799e"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-linux-arm64.tar.gz"
    end
  end

  name "preflight"
  desc "Deterministic workstation compiler"
  homepage "https://github.com/felixgeelhaar/preflight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preflight"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/preflight"]
    end
  end

  # No zap stanza required

end
