# This file was generated by GoReleaser. DO NOT EDIT.
cask "preflight" do
  version "4.12.1"

  on_macos do
    on_intel do
      sha256 "b8197db4fe7a176577945db3fb71d1705e72cf6301253733f56426557ec68547"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "1c49c8f170e192de3179718888842ef63df23e87617547a48bc96a8d274a3723"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a61211baedec9b67a0f8e7cd270a475e40cc2e5aae0e2e01075801750e73ab1a"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "592408b1af614322be7de108b66542974f87ad442a2b6543aa1fb8b65ccd0c58"
      url "https://github.com/felixgeelhaar/preflight/releases/download/v#{version}/preflight-linux-arm64.tar.gz"
    end
  end

  name "preflight"
  desc "Deterministic workstation compiler"
  homepage "https://github.com/felixgeelhaar/preflight"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "preflight"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/preflight"]
    end
  end

  # No zap stanza required

end
