# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "094d6ac58a32c5d152742746af4a2a90839837a100d21c552e5533f2d3aa0f30"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed32121fd1270df9537b138fb433ea5e4e26136945281c5e68ec56bc1b58f302"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9633f512524e1193c4046e4e03ee6a42f85f14bc18dc9fee326e24ca9b630702"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "241cb32f93884513686c6872dfe7c7466260d5dd0ced51c5adef7af7e2463f96"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
