# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.18.10"

  on_macos do
    on_intel do
      sha256 "6974ab9358b8e4d30a4757dcf5db219c7d6c491dbf06e3f2f43f54f7ce671d37"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1e7a74b8f574ecf2abee8044958f4b4e1bfc09d6a0b68e588b93b3ab90a6841"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ced0f499472c2e4f47ded5257c3e939925414ce8f83aa04dea5f0d6783e285ee"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2498df8417897243c21a2081e8492d0558ed9611cc1dc4c352ae01171a4f2423"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
