# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.18.11"

  on_macos do
    on_intel do
      sha256 "bca6812bb12f4f144a7caa8ff1c0acb61d586933766e38bec47ae6344faa1e1f"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b30705a89ccf27761536a27483f854b7ed94be8483ece480e42369fec1438974"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0788a704767d12856e7284e99b93111986e8d6af9cae5dcaf7cc8d13c22a21eb"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2887cf63fca679710c8beaa86b59ce4b0589af5801ca8459ebd9fc80a75c837a"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
