# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acai < Formula
  desc "Go CLI and MCP server for Granola meeting intelligence"
  homepage "https://github.com/felixgeelhaar/acai"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.0.0/acai_2.0.0_darwin_amd64.tar.gz"
      sha256 "02ca06a063916bb9fbda5cc14b338a0c052123e430a97d36b00c9ef7d413bbf6"

      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.0.0/acai_2.0.0_darwin_arm64.tar.gz"
      sha256 "605c8fece5240fa2354f218e57b7429f186def4d73be4185b307d98716cbdb14"

      def install
        bin.install "acai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.0.0/acai_2.0.0_linux_amd64.tar.gz"
      sha256 "d5a4b37acc990b520e3554f3c553eafa86e90524e28762cb03930505ee2be11f"
      def install
        bin.install "acai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/acai/releases/download/v2.0.0/acai_2.0.0_linux_arm64.tar.gz"
      sha256 "2c0c01011c0c263e899d697bcd99c39e0e8704f8b2dfc815025fd511306379dc"
      def install
        bin.install "acai"
      end
    end
  end
end
