# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronos < Formula
  desc "Time / Pattern Perception in the cognitive stack"
  homepage "https://github.com/felixgeelhaar/chronos"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.1.0/chronos_0.1.0_darwin_x86_64.tar.gz"
      sha256 "3a719f28ff818835b25724eff4b84a48ee5daf245be95c072dc0c2d8c99bf3dc"

      define_method(:install) do
        bin.install "chronos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.1.0/chronos_0.1.0_darwin_arm64.tar.gz"
      sha256 "9e5abc005563b08a676e05be3a336cc5f23012ecad7d097aafe904da7f57a7dc"

      define_method(:install) do
        bin.install "chronos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.1.0/chronos_0.1.0_linux_x86_64.tar.gz"
      sha256 "93198f40f75d635ee93e1ec2fc4b610517dccd86341f84c96e48159d095faf1e"
      define_method(:install) do
        bin.install "chronos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.1.0/chronos_0.1.0_linux_arm64.tar.gz"
      sha256 "357b1fc41fb0cb4d768481bdd1b67ad4a68f82b54186cd0cc043eb48b597575d"
      define_method(:install) do
        bin.install "chronos"
      end
    end
  end

  test do
    system "#{bin}/chronos", "version"
  end
end
