# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronos < Formula
  desc "Time / Pattern Perception in the cognitive stack"
  homepage "https://github.com/felixgeelhaar/chronos"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.6.0/chronos_0.6.0_darwin_x86_64.tar.gz"
      sha256 "1fd4da6feced3915d42bc1ef4761389a4bb0a09605028a7392d382d2c02403d9"

      define_method(:install) do
        bin.install "chronos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.6.0/chronos_0.6.0_darwin_arm64.tar.gz"
      sha256 "e053afc989fb7c31db87e45a34007e4cc6643ebe762d9e3617ac4973dc770d08"

      define_method(:install) do
        bin.install "chronos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.6.0/chronos_0.6.0_linux_x86_64.tar.gz"
      sha256 "456dfe6d13c4e88ddf03c25dd94f658fb5051107cdf2f5f8cf7a7cced225cf74"
      define_method(:install) do
        bin.install "chronos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/chronos/releases/download/v0.6.0/chronos_0.6.0_linux_arm64.tar.gz"
      sha256 "ab9e61b76684a874d73f8e71127fd80caabe77cdf290458598f90ff347e9449c"
      define_method(:install) do
        bin.install "chronos"
      end
    end
  end

  test do
    system "#{bin}/chronos", "version"
  end
end
