# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/felixgeelhaar/mnemos"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.6.1/mnemos_0.6.1_darwin_amd64.tar.gz"
      sha256 "bdef6645be2ffb363fcbd6fc3e9cc0d43142ebe3887a8ce93c70e33beeab4647"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.6.1/mnemos_0.6.1_darwin_arm64.tar.gz"
      sha256 "0def916f38830f3bde0336e92f68d159a851593d3c59658be08766378988b054"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.6.1/mnemos_0.6.1_linux_amd64.tar.gz"
      sha256 "be08b5494575ef83756c0b0637dfcd5ea440de17987f96c6fd88e3cfb29cda28"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.6.1/mnemos_0.6.1_linux_arm64.tar.gz"
      sha256 "3cd3c530e3b99b06f9999e5aeec8df8738f935ea62b02a00cfc7a5a0f25d761e"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
