# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/felixgeelhaar/mnemos"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.5.1/mnemos_0.5.1_darwin_amd64.tar.gz"
      sha256 "e0b260809864f6c2eb6a36406bdd1b2e06a8e90e4e85587eecf1c9d0e83f7cf2"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.5.1/mnemos_0.5.1_darwin_arm64.tar.gz"
      sha256 "92de27dff6fdbc7d0be9b2cce13e3d77f94086f732f660db4e9f50d36c8e6b3b"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.5.1/mnemos_0.5.1_linux_amd64.tar.gz"
      sha256 "adcc1a8f262f5fe7a25738c9c02121945174374ad726af050c96b7f265267621"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.5.1/mnemos_0.5.1_linux_arm64.tar.gz"
      sha256 "fdce33860966aa5017778abb8ed9b02a771d64ed33d73b5906d57de2a078cbdc"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
