# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/felixgeelhaar/mnemos"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.11.0/mnemos_0.11.0_darwin_amd64.tar.gz"
      sha256 "b8472dbbfe83897f94d4e69f8f2a5a14d42fdf137c7917a1fbb71882565b30c4"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.11.0/mnemos_0.11.0_darwin_arm64.tar.gz"
      sha256 "05cd4adb5ac38e2ff61292295f33d239c9cc4b846c84fcc31fa91bd3235bb843"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.11.0/mnemos_0.11.0_linux_amd64.tar.gz"
      sha256 "5f483458919883f276750fad340422f749e18e306e87ad71b6788d14ecaf2d84"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/Mnemos/releases/download/v0.11.0/mnemos_0.11.0_linux_arm64.tar.gz"
      sha256 "ed0cc9a791fa217f881e858ec2b667c8bc2d45affd59188bf72c6d0ebe1ecae7"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
