# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nous < Formula
  desc "Decision / coordination layer of the cognitive stack"
  homepage "https://github.com/felixgeelhaar/nous"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.2.0/nous_0.2.0_darwin_x86_64.tar.gz"
      sha256 "52bcf89af57e985cb3cd2de6adcdcf0bb5d8414c4ca4711a9ba427aa530cd4a4"

      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.2.0/nous_0.2.0_darwin_arm64.tar.gz"
      sha256 "84d54bc82a14c6cd9c2f790026a144d0a925096f3db81e4a674b82c2feb5336b"

      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.2.0/nous_0.2.0_linux_x86_64.tar.gz"
      sha256 "71874dba596ff8b0fe280a21b78f7b1c6b8261aef14fe283bf3c7674a5708bb8"
      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.2.0/nous_0.2.0_linux_arm64.tar.gz"
      sha256 "0aea149e4d418a523818727b2065c35d18e1887ebd02de740cd569a471eaa5d2"
      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  test do
    system "#{bin}/nous", "version"
  end
end
