# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nous < Formula
  desc "Decision / coordination layer of the cognitive stack"
  homepage "https://github.com/felixgeelhaar/nous"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.1.1/nous_0.1.1_darwin_x86_64.tar.gz"
      sha256 "fb0b656570a61f15d4813a355b53ea36feb379d1dc8d4beac3b40032ed9fbc94"

      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.1.1/nous_0.1.1_darwin_arm64.tar.gz"
      sha256 "689d2681da95f723f2d2f15486ab5d4907f5e9632f6ddb699c5eb8c206d0a5b2"

      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.1.1/nous_0.1.1_linux_x86_64.tar.gz"
      sha256 "db7e26a16da6dec1c76895be5be9146416ddeb0006c8ef923ca3c56988c6f6d4"
      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.1.1/nous_0.1.1_linux_arm64.tar.gz"
      sha256 "dffc1d1e5d8d72937fba63ee811af986df7b51b303ec34f43b27336671eee31a"
      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  test do
    system "#{bin}/nous", "version"
  end
end
