# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nous < Formula
  desc "Decision / coordination layer of the cognitive stack"
  homepage "https://github.com/felixgeelhaar/nous"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.3.0/nous_0.3.0_darwin_x86_64.tar.gz"
      sha256 "74e04009ab1c45d7bfeb197cc30643def9f708eae23e6bc495fc15b159d0a9d7"

      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.3.0/nous_0.3.0_darwin_arm64.tar.gz"
      sha256 "d238d330f5517d565585c7dcda7c28dc1a06f3831995193994853a1a121d178a"

      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.3.0/nous_0.3.0_linux_x86_64.tar.gz"
      sha256 "7bd15814351bb67e1db3e6c14555defc75e24dfb4caff331e627a5e76e577e4e"
      define_method(:install) do
        bin.install "nous"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/nous/releases/download/v0.3.0/nous_0.3.0_linux_arm64.tar.gz"
      sha256 "4bd43e3ff47a37021c4f60f13620d5a611c3a5346e228c1666ceb48b93fe1c3c"
      define_method(:install) do
        bin.install "nous"
      end
    end
  end

  test do
    system "#{bin}/nous", "version"
  end
end
