# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "0.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nox-hq/nox/releases/download/v0.9.1/nox_0.9.1_darwin_amd64.tar.gz"
      sha256 "21c6376a25ed80aba6da24574583b6e66205590c05e085b37a9882be6088d3f2"

      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nox-hq/nox/releases/download/v0.9.1/nox_0.9.1_darwin_arm64.tar.gz"
      sha256 "1d4f5ebcee121ec5923b5cc492e6a05e0457f741fe91d08f2decc867079a23d6"

      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.9.1/nox_0.9.1_linux_amd64.tar.gz"
      sha256 "200f54d01aaf24bacfaa7fd06f98ee1e82638e27f972cac8d3ea20374fd17f6f"
      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v0.9.1/nox_0.9.1_linux_arm64.tar.gz"
      sha256 "0f8c4e5148465f58cae725f3fb7b9be6a05fb6a9ebbed3c422cb1c3df0c57e55"
      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
  end

  test do
    system "#{bin}/nox", "--help"
    system "#{bin}/nox-plugin-reachability", "--help" rescue true
  end
end
