# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "Language-agnostic security scanner with first-class AI application security"
  homepage "https://github.com/nox-hq/nox"
  version "1.13.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nox-hq/nox/releases/download/v1.13.1/nox_1.13.1_darwin_amd64.tar.gz"
      sha256 "60bc2088bec09f26d4c1da9d5bdae841e18dcca6e5270161f85a511b68c7942e"

      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nox-hq/nox/releases/download/v1.13.1/nox_1.13.1_darwin_arm64.tar.gz"
      sha256 "ba3a26b18e96832903dc47bf6d920f02e28375cb81a835acd261982478537b85"

      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v1.13.1/nox_1.13.1_linux_amd64.tar.gz"
      sha256 "5f5077aa1ffc4798ad4656d1c83075c57cc257e344a05dd7e12dbb65ecd6c81c"
      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nox-hq/nox/releases/download/v1.13.1/nox_1.13.1_linux_arm64.tar.gz"
      sha256 "532ec4948ca238dffd7d363e40997d13fa391d39c0d18cda416cc9c6bee4e59d"
      define_method(:install) do
        bin.install "nox"
        bin.install "bin/nox-plugin-reachability"
      end
    end
  end

  test do
    system "#{bin}/nox", "--help"
    system "#{bin}/nox-plugin-reachability", "--help" rescue true
  end
end
