# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praxis < Formula
  desc "Praxis — execution layer of the Mnemos/Chronos/Nous/Praxis cognitive stack"
  homepage "https://github.com/felixgeelhaar/praxis"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.2.1/praxis_0.2.1_darwin_amd64.tar.gz"
      sha256 "bba17e361f4d3a50d2375987587772c919795adf0fc2b23e99be100bd8c4c224"

      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.2.1/praxis_0.2.1_darwin_arm64.tar.gz"
      sha256 "8840d06d2262012a1dd48dac2d6e3451296b40baeeeaf0a80d86bbe5ba85879c"

      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.2.1/praxis_0.2.1_linux_amd64.tar.gz"
      sha256 "9b7cdf96d7e74c2721b14230e39a3a25ea4bc52fa6cd1a20b7156db61338f8d1"
      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.2.1/praxis_0.2.1_linux_arm64.tar.gz"
      sha256 "00af482cfeffe8c03a908d1928c79dd056e9466198df1e38c88575116fb05640"
      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
  end

  test do
    system bin/"praxis", "version"
  end
end
