# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Praxis < Formula
  desc "Praxis — execution layer of the Mnemos/Chronos/Nous/Praxis cognitive stack"
  homepage "https://github.com/felixgeelhaar/praxis"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.3.0/praxis_0.3.0_darwin_amd64.tar.gz"
      sha256 "7119f06132ac5ef6493696dcbfd7d4c4d4efdfa3d18831417e88a05dcd086b3c"

      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.3.0/praxis_0.3.0_darwin_arm64.tar.gz"
      sha256 "d7da23ff11d9ee2b0eb6b328809b10b1336691bce8dd9e78dd7461a1d9c3bbcd"

      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.3.0/praxis_0.3.0_linux_amd64.tar.gz"
      sha256 "568719dbcb1c21f35a79244230c76f73ab703978784e3777830224cd2481f1e0"
      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/praxis/releases/download/v0.3.0/praxis_0.3.0_linux_arm64.tar.gz"
      sha256 "9df86d7035719d3ddb161fff138b6d61b3cced120fef44fe98ee57593e3e9720"
      define_method(:install) do
        bin.install "praxis"
        bin.install "praxis-pluginhost"
      end
    end
  end

  test do
    system bin/"praxis", "version"
  end
end
