# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Preflight < Formula
  desc "Deterministic workstation compiler"
  homepage "https://github.com/felixgeelhaar/preflight"
  version "4.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/preflight/releases/download/v4.11.0/preflight-darwin-amd64.tar.gz"
      sha256 "51355d3949482f47850e41274c973af1c7c1814febf7d527ecf1834ecba4be13"

      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/preflight/releases/download/v4.11.0/preflight-darwin-arm64.tar.gz"
      sha256 "2fb432f1fb5c5f6975b62c0377a591de51aea9530490df9422b1eba43f399bb4"

      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/preflight/releases/download/v4.11.0/preflight-linux-amd64.tar.gz"
      sha256 "54c7dcbb076b87bc3b04cf4d201f9faecd10f3ebc4aec9c175e0c037b7743db3"
      define_method(:install) do
        bin.install "preflight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/preflight/releases/download/v4.11.0/preflight-linux-arm64.tar.gz"
      sha256 "b6cee7c7e239790e0a0979a070dc59a069632bf3934a9ebfc23ce110b291e097"
      define_method(:install) do
        bin.install "preflight"
      end
    end
  end

  test do
    system "#{bin}/preflight", "version"
  end
end
