# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.11.1/roady_Darwin_x86_64.tar.gz"
      sha256 "a211a4b2ab8473a0dd92a272890c61b18a2b4f18ee44d9b070377fd0cdcc1de8"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.11.1/roady_Darwin_arm64.tar.gz"
      sha256 "4d4dc940faae285f32c7a12571ff38f54447064ab9bc15a20b94409d4eb5b1a1"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.11.1/roady_Linux_x86_64.tar.gz"
      sha256 "693d72d113aa7de5d297e8eac69a7293166125f9524bf2d30d3f8247bb8b0010"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.11.1/roady_Linux_arm64.tar.gz"
      sha256 "111b70660180de90b9d6be93be898e49f25f499fe1c300c000601333bfec4c9e"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  test do
    system "#{bin}/roady --version"
  end
end
