# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.4.1/roady_Darwin_x86_64.tar.gz"
      sha256 "d922b8ddd753105428ccde33feade8d5965796c73126ccb266da904296019910"

      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.4.1/roady_Darwin_arm64.tar.gz"
      sha256 "125fde858f648197cc82965c1884f86a658f76e50e9b2536b1512d20d5119b4c"

      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.4.1/roady_Linux_x86_64.tar.gz"
      sha256 "7a8f44b605bd99b6fceb7b1c394e6f1555bf568bb6406477811ddac3a5664ad4"
      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.4.1/roady_Linux_arm64.tar.gz"
      sha256 "40615b74d3090b7013261b094fdc1fa169d97442f707857dfa2de82038f0c667"
      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
  end
end
