# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.7.3/roady_Darwin_x86_64.tar.gz"
      sha256 "92ab8e7451b35a71a4588e3883596b8d1dae546689480514727c6994c852a420"

      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.7.3/roady_Darwin_arm64.tar.gz"
      sha256 "721f38ee9c86e85c11b7194b26875cf11ed50668824834dce29e9c57e355a0a2"

      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.7.3/roady_Linux_x86_64.tar.gz"
      sha256 "544bbb85f8bd78ba456da3d61b85c0017bb95c72af64846e8a1a4462807a47ff"
      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.7.3/roady_Linux_arm64.tar.gz"
      sha256 "ad1fb35791aaf54785611a9a879bf5030f573e89c0135ebd8c6baa5c4aace753"
      def install
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
      end
    end
  end
end
