# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/felixgeelhaar/scout"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.1.0/scout_0.1.0_darwin_amd64.tar.gz"
      sha256 "bc9c7069707223a9a9a4bf92b1927920557e15d34c58decc4f2ddbd9c8641b22"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.1.0/scout_0.1.0_darwin_arm64.tar.gz"
      sha256 "bb8e514ffddcfddb6a4eb5a47dff5808c85fc1397a8fabd58810f3cd96bfc8ff"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.1.0/scout_0.1.0_linux_amd64.tar.gz"
      sha256 "f50fd5f0c150275a80ce9590d9a84ad6c08d37a431fcce52ae9a75dd8e2bb213"
      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.1.0/scout_0.1.0_linux_arm64.tar.gz"
      sha256 "1eba4c2b5fa800335cc2b4f1d2f9c4406fbbc3592966e8abb108c53229f9445a"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
