# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/felixgeelhaar/scout"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scout/releases/download/v1.0.2/scout_1.0.2_darwin_amd64.tar.gz"
      sha256 "36f4dec937f521ccdacc6140e4e99ba449967317dfe015112821c9c95437c5e7"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scout/releases/download/v1.0.2/scout_1.0.2_darwin_arm64.tar.gz"
      sha256 "1354fbe878516a69c5a3a26ba92b9da9328ee5a129a40e677d2da0a533d85844"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v1.0.2/scout_1.0.2_linux_amd64.tar.gz"
      sha256 "6a9be026680a8a037d1f5e7ccadf4e70dd2ba06b90999471d771970baeff1f2f"
      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v1.0.2/scout_1.0.2_linux_arm64.tar.gz"
      sha256 "f9641b7ceae1cb67a70cc182e100ba0152d7439bf1165da971bbbc5d79f6de4c"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
