# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/felixgeelhaar/scout"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.4.0/scout_0.4.0_darwin_amd64.tar.gz"
      sha256 "8bff155c3c1f88e9eb1d17b918a9a63506e93263d32f6c2fc9c32f999c64a77d"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.4.0/scout_0.4.0_darwin_arm64.tar.gz"
      sha256 "b48687ac573b80ecb63c966685f940ab2d2c790ab66256e734bdeef73006017e"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.4.0/scout_0.4.0_linux_amd64.tar.gz"
      sha256 "97f9bd97474be083f5e83434e79707f39275d0eb4c4e0c6f3899aea7b9d95cc5"
      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scout/releases/download/v0.4.0/scout_0.4.0_linux_arm64.tar.gz"
      sha256 "3371c44a91fc8ec6e24b4df54d539b1cb8fb56e99345fe709d4b1091c4646a91"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
