# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scry < Formula
  desc "Searchable GraphQL ↔ MCP bridge for AI agents"
  homepage "https://github.com/felixgeelhaar/scry"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.8.0/scry_0.8.0_darwin_amd64.tar.gz"
      sha256 "db90e8908507ebcc93ac745f511bb25adcdf0ee0777bd9cceb881f3f2acae87f"

      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.8.0/scry_0.8.0_darwin_arm64.tar.gz"
      sha256 "64b5f8bbb45a55b6f776c796f6ee7cdab32e241f09ac9ab6ece11babeb27c199"

      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.8.0/scry_0.8.0_linux_amd64.tar.gz"
      sha256 "a1f82a32fae3c2d2a9b2cc8ef1e97d0ca7ae433e8edc405f0b7869c29540fe32"
      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.8.0/scry_0.8.0_linux_arm64.tar.gz"
      sha256 "78d83705e8c49316a1335705928dd27f0c5acc13990a098b2b7e7f06f9015070"
      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  test do
    system "#{bin}/scry", "version"
  end
end
