# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scry < Formula
  desc "Searchable GraphQL ↔ MCP bridge for AI agents"
  homepage "https://github.com/felixgeelhaar/scry"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.4.1/scry_0.4.1_darwin_amd64.tar.gz"
      sha256 "1e7fe2e2ee2ea1f3aacb127aea4774fd632528e27811181aa9f0d027c8ad0789"

      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.4.1/scry_0.4.1_darwin_arm64.tar.gz"
      sha256 "4f1219f430462b70ff9f0a09a2c7c88a58fea359c960c4abece84c36f427b221"

      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.4.1/scry_0.4.1_linux_amd64.tar.gz"
      sha256 "8ee3f91d4e53040bd276662e29830b6cc0762026291df9a14c9b75e0b0a06cda"
      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.4.1/scry_0.4.1_linux_arm64.tar.gz"
      sha256 "848a7efe0f9f2d63070c7307913426472b64232fd0e60e122094600f4db98390"
      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  test do
    system "#{bin}/scry", "version"
  end
end
