# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scry < Formula
  desc "Searchable GraphQL ↔ MCP bridge for AI agents"
  homepage "https://github.com/felixgeelhaar/scry"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.7.2/scry_0.7.2_darwin_amd64.tar.gz"
      sha256 "7ffafb7ebc422e8f67367064ed7c5ff3117512d908b35082e668c723d7759ad9"

      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.7.2/scry_0.7.2_darwin_arm64.tar.gz"
      sha256 "d076e6521cc6a87332fa2e94f94f33c69a4c7e83c7ba5b95615092c39f8a9ffc"

      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.7.2/scry_0.7.2_linux_amd64.tar.gz"
      sha256 "18ec890c7b8bc316f49c7363d1f501d9e9bed3ad3bf8e492a7eb8a2a9d42487e"
      define_method(:install) do
        bin.install "scry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/scry/releases/download/v0.7.2/scry_0.7.2_linux_arm64.tar.gz"
      sha256 "b3f6c07ac8c426458ef27281da300a2c12a32136cb64d033df723bb3150c7c1d"
      define_method(:install) do
        bin.install "scry"
      end
    end
  end

  test do
    system "#{bin}/scry", "version"
  end
end
