# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simon < Formula
  desc "AI Agent Governance Runtime - Deterministic control plane for AI agents."
  homepage "https://github.com/felixgeelhaar/simon"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.2.0/simon_Darwin_x86_64.tar.gz"
      sha256 "db3f02b6e4c2093b1b5098de67ee33b89bbdb7b7fcff89aeda71f0ab1328d4b0"

      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.2.0/simon_Darwin_arm64.tar.gz"
      sha256 "f1254a02caf59fec11d47e60c28b0f329f76009ae90da40784ea4e00bc163a59"

      def install
        bin.install "simon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.2.0/simon_Linux_x86_64.tar.gz"
      sha256 "e6826cd4394cbeaf9403d81bb38de5e6dc579efe801c9501c990cf134aa57518"
      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.2.0/simon_Linux_arm64.tar.gz"
      sha256 "a09bdb92b27226dd11617729d07e8a8d28c95647526f80036a3a6e5f69f96551"
      def install
        bin.install "simon"
      end
    end
  end
end
