# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simon < Formula
  desc "AI Agent Governance Runtime - Deterministic control plane for AI agents."
  homepage "https://github.com/felixgeelhaar/simon"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.0/simon_Darwin_x86_64.tar.gz"
      sha256 "612872b5a6f6d92eb4c7056df76e82f212b162dae20a7189a0090c1b6c07f4dc"

      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.0/simon_Darwin_arm64.tar.gz"
      sha256 "48736c3d34410feba67d43b32ac5754d91af16ca157d6d6f39efee7d5911165f"

      def install
        bin.install "simon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.0/simon_Linux_x86_64.tar.gz"
      sha256 "455872b6945815626b8431a657c2e077043ea5ae14dbb3dd623c66ce72378fc6"
      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.0/simon_Linux_arm64.tar.gz"
      sha256 "65b666167d27fc72e43c9c8bc72ea6078270fc9e4ab81a84a81a2e3c66a00787"
      def install
        bin.install "simon"
      end
    end
  end
end
