# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simon < Formula
  desc "AI Agent Governance Runtime - Deterministic control plane for AI agents."
  homepage "https://github.com/felixgeelhaar/simon"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.1/simon_Darwin_x86_64.tar.gz"
      sha256 "7a09ac1c38370856dd1bc9bdbba55c1e34983d7460ad6c053af2f820bcce5924"

      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.1/simon_Darwin_arm64.tar.gz"
      sha256 "ea7faa346b730ffc8f32cd305960d90cbd4d5b29d07e69e8ad60af242bbce1cc"

      def install
        bin.install "simon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.1/simon_Linux_x86_64.tar.gz"
      sha256 "c384ff8b620268cdecc8a8e12e9f29ef95d3e4322ffcdf9eae68a42a0915ccc0"
      def install
        bin.install "simon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/simon/releases/download/v0.1.1/simon_Linux_arm64.tar.gz"
      sha256 "8a3703c7b3c40fb718c73520b0ebd518f2e7268244306e0e2d7974ae406d3d78"
      def install
        bin.install "simon"
      end
    end
  end
end
