# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specular < Formula
  desc "AI-Native Spec and Build Assistant with policy enforcement"
  homepage "https://github.com/felixgeelhaar/specular"
  version "1.0.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.0.1/specular_1.0.1_darwin_amd64.tar.gz"
      sha256 "0a02a428c88142750aac385dd4f7ee08c850a23239c81b7e50a9a5fc8206212e"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.0.1/specular_1.0.1_darwin_arm64.tar.gz"
      sha256 "0fb89b09716f51aa24cb74ac9c5b9afb5301a133bde403501bd56bea5ac2808d"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.0.1/specular_1.0.1_linux_amd64.tar.gz"
      sha256 "134aa5d0a0683e9491722272a8403d5112889f32b51b72809bb8901a55cfdc7c"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.0.1/specular_1.0.1_linux_arm64.tar.gz"
      sha256 "f04ba128fb4680fb068ddcea249d18457c05a82bd631cd375e467de597ac781e"
      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  test do
    system "#{bin}/specular", "version"
  end
end
