# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specular < Formula
  desc "AI-Native Spec and Build Assistant with policy enforcement"
  homepage "https://github.com/felixgeelhaar/specular"
  version "1.4.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_darwin_amd64.tar.gz"
      sha256 "310c241b8dc260bdb21063d7543513d0f030b3f42efd30e179ed353645b08ad6"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_darwin_arm64.tar.gz"
      sha256 "e8eadf6162dbf5d373009d816f90c9a1755b4d7135894bccc06085a677165d57"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_linux_amd64.tar.gz"
      sha256 "bb4e6213a919268adc64f86ae47d5c239ae204e1fcbbc256ed9d5596f658e96a"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_linux_arm64.tar.gz"
      sha256 "ed7e3932d901f956524a63b620c6487c835db65b6addbfdbf9e7f263b89db3de"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  test do
    system "#{bin}/specular", "version"
  end
end
