# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specular < Formula
  desc "AI-Native Spec and Build Assistant with policy enforcement"
  homepage "https://github.com/felixgeelhaar/specular"
  version "1.4.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_darwin_amd64.tar.gz"
      sha256 "6f89d1c100384064a97adaae0fec78757273b456c51124b6d140b89a2654ba0a"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_darwin_arm64.tar.gz"
      sha256 "fd82d057bc0414f65b5423a207b9fdb6b50c8acaea6779934eccb594e2243e83"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_linux_amd64.tar.gz"
      sha256 "f3a39c407a3febd59536422b7d1a971f853a57d09f2f5481c4978f93e90d2f4b"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/specular/releases/download/v1.4.0/specular_1.4.0_linux_arm64.tar.gz"
      sha256 "8152440972350fe0ef18e8f82e91ad6ff9a290f08d1be35b357a7aa356d0542a"

      def install
        bin.install "specular"

        # Install shell completions
        bash_completion.install "completions/specular.bash" => "specular"
        zsh_completion.install "completions/_specular" => "_specular"
        fish_completion.install "completions/specular.fish"
      end
    end
  end

  test do
    system "#{bin}/specular", "version"
  end
end
