# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Temper < Formula
  desc "Adaptive AI pairing for learning"
  homepage "https://github.com/felixgeelhaar/temper"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.1/temper_2.0.1_darwin_amd64.tar.gz"
      sha256 "34fa94de30c414f2e07efed75ede2be891d840414cfbf81116f7d8b801b990d7"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.1/temper_2.0.1_darwin_arm64.tar.gz"
      sha256 "d6fd14ec2b89e8e0895ca2ef2b91ab7fdde97b5c9212cf47709ba5f55a0389b7"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.1/temper_2.0.1_linux_amd64.tar.gz"
      sha256 "bfd4385417033c9a8b18294c2626066759641368cdc3650249381c26240a9c19"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.1/temper_2.0.1_linux_arm64.tar.gz"
      sha256 "3cbb93606ddbfe1e07a00d186dee65609fb558c9eb4fafdc11011f232b4227f7"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  test do
    system "#{bin}/temper", "--version"
  end
end
