# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Temper < Formula
  desc "Adaptive AI pairing for learning"
  homepage "https://github.com/felixgeelhaar/temper"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.2/temper_2.0.2_darwin_amd64.tar.gz"
      sha256 "29544abe855ea47e52e052aedaeb503049632dfb893c476175478d9f89400287"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.2/temper_2.0.2_darwin_arm64.tar.gz"
      sha256 "d350229a86a4557bb10d597140946947900697ea2be0ff32556e984e591d8049"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.2/temper_2.0.2_linux_amd64.tar.gz"
      sha256 "a87b87f8dcf738b24bd7f27f7793c6b71d3890c54d00296278abb9a05bc8cb17"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.0.2/temper_2.0.2_linux_arm64.tar.gz"
      sha256 "0fed257de724120709beafadc0ffc206d10631f557d55f82d98c9e96dc16e15e"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  test do
    system "#{bin}/temper", "--version"
  end
end
