# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Temper < Formula
  desc "Adaptive AI pairing for learning"
  homepage "https://github.com/felixgeelhaar/temper"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.1.0/temper_2.1.0_darwin_amd64.tar.gz"
      sha256 "3f6543e61c8ad15a98332afc2fde582b2579e54966567ba89b6080dfa3d45a0c"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.1.0/temper_2.1.0_darwin_arm64.tar.gz"
      sha256 "2a0ae611905977e2fe722f8265712c7b0e33f745e2d4953553d6525c62a5c68d"

      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.1.0/temper_2.1.0_linux_amd64.tar.gz"
      sha256 "4acbdc0757926224dfe4f0cc7596eb4406a9a5c7092689673abf3c20fc78edca"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/temper/releases/download/v2.1.0/temper_2.1.0_linux_arm64.tar.gz"
      sha256 "eb2d0f160acd460cdd170584e515af836bfbd71cb1a425b4375fd5b430959703"
      define_method(:install) do
        bin.install "temper"
        bin.install "temperd"
      end
    end
  end

  test do
    system "#{bin}/temper", "--version"
  end
end
