# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenops < Formula
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/felixgeelhaar/tokenops"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/tokenops/releases/download/v0.4.0/tokenops_0.4.0_darwin_amd64.tar.gz"
      sha256 "06cbb29a747169ea0796dcd7dc00dbf43060e6c0391d53450255502b4f769d7d"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/tokenops/releases/download/v0.4.0/tokenops_0.4.0_darwin_arm64.tar.gz"
      sha256 "f1a651430d5bf10456ba7d7bf4ae943daf1e4c75b50d7c1ab471d81119c5fbeb"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/tokenops/releases/download/v0.4.0/tokenops_0.4.0_linux_amd64.tar.gz"
      sha256 "b1e491d91f6cd84289c333ae2a34a43172c40f3ff99470010330b3ed2d7e9d3c"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/tokenops/releases/download/v0.4.0/tokenops_0.4.0_linux_arm64.tar.gz"
      sha256 "d3500814e0de88bf4998100df55009ea34a2a73b8699525083246b5600fce257"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  test do
    system "#{bin}/tokenops", "version"
    system "#{bin}/tokenopsd", "version"
  end
end
