# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenops < Formula
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"
  version "0.32.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.32.0/tokenops_0.32.0_darwin_amd64.tar.gz"
      sha256 "c6a86dc85a1a9e20ef1d301a306a2d1f8ae83eea753d4836442f16de1fb19306"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.32.0/tokenops_0.32.0_darwin_arm64.tar.gz"
      sha256 "9dedc20ee29ea0b378006a47eca5334474d312cb4f4add76d184435d78cf6667"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.32.0/tokenops_0.32.0_linux_amd64.tar.gz"
      sha256 "e927194311d7e78e004df85834149f5bc65793e46f6e97e06036b4076d53608d"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.32.0/tokenops_0.32.0_linux_arm64.tar.gz"
      sha256 "7944c4cae442c313ea30dd8f31951b139cbcdc8f9db1f25635989b0e219c9c4a"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  test do
    system "#{bin}/tokenops", "version"
    system "#{bin}/tokenopsd", "version"
  end
end
