# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verdict < Formula
  desc "Go security assessment CLI - SAST, vulnerabilities, secrets, SBOM"
  homepage "https://github.com/felixgeelhaar/verdictsec"
  version "0.11.2"
  license "Apache-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/verdictsec/releases/download/v0.11.2/verdict_0.11.2_darwin_amd64.tar.gz"
      sha256 "08bda4bef0f906e7e597ab2376b44e610b702fb09dbae538f6c3b80a55b44a37"

      def install
        bin.install "verdict"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/verdictsec/releases/download/v0.11.2/verdict_0.11.2_darwin_arm64.tar.gz"
      sha256 "fd58659f32301e92b6f1bb095f6d449ad7f5b0f2700feb7a60abbcacb5d55a08"

      def install
        bin.install "verdict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/verdictsec/releases/download/v0.11.2/verdict_0.11.2_linux_amd64.tar.gz"
      sha256 "d106eab2f9ab6e3a50c4cbf2c540ae4afbb3f2286269cb4ade2e8a72134b3623"
      def install
        bin.install "verdict"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/verdictsec/releases/download/v0.11.2/verdict_0.11.2_linux_arm64.tar.gz"
      sha256 "b7707cde7a5c907be18426a3e7efa8bfcb248ce3ff5da1eba5366ec328fdc687"
      def install
        bin.install "verdict"
      end
    end
  end

  test do
    system "#{bin}/verdict", "--version"
  end
end
